VP_Lifestyle/Controllers/AdminHomeController.cs
using VP_Lifestyle.Data;
using VP_Lifestyle.Models;
using VP_Lifestyle.Models.ProductMenuViewModel;
using Microsoft.AspNetCore.Mvc;

namespace VP_Lifestyle.Controllers
{
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
    }
}

VP_Lifestyle/Controllers/AdminProductController.cs
using VP_Lifestyle.Data;
using VP_Lifestyle.Models;
using VP_Lifestyle.Models.ProductMenuViewModel;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.ComponentModel.DataAnnotations;
using System.Drawing;

namespace VP_Lifestyle.Controllers
{
    public class AdminProductController : Controller
    {
        //Create a readonly variables for interface type
        private readonly ILifestyleRepository _LifestyleRepository;
        private readonly IEnumerable<Category> _categories; //Will store the category data
        
        public AdminProductController(ILifestyleRepository lifestyleRepository)
        {
            _LifestyleRepository = lifestyleRepository;
            _categories = _LifestyleRepository.GetAllCategories()
                          .OrderBy(cat => cat.CategoryName);
        }
        public IActionResult Product(string id ="all")
        {
            //create an IEnumerable to store the product
            IEnumerable<Product> products;

            if (id == "all")
            {
                products = _LifestyleRepository.GetAllProduct()
                           .OrderBy(pro => pro.ProductName).ToList();
            }
            else
            {
               products = _LifestyleRepository.GetAllProductsWithCategoryDetails()
                           .Where(pro => pro.Category.CategoryName.ToLower() == id.ToLower())
                           .OrderBy(pro => pro.ProductName).ToList();
            }
            //instatiate a ProductListViewModel 

            var model = new ProductMenuViewModel
            {
                Categories = _categories,
                Products = products,
                SelectedCategory = id
            };

            //Create a viewbag to temporary store categories 
            //and the selecteed category id/name
            ViewBag.Categories = _categories;
            ViewBag.SelectedCategoryName = id;

            return View(model);
        }

        //Add
        [HttpGet] //Retrieves data from the server e.g fetching the webpage.
        public IActionResult Add()
        {
            //Add default category object to avoid validation issue
           // Category category = _LifestyleRepository.GetCategoryById(1);
            //Viewbag to indicate the type of action being performed
            ViewBag.Categories = _LifestyleRepository.GetAllCategories();
            ViewBag.Action = "Add";
            // bind product to AddUpdate view
            return View("AddUpdate", new Product());

        }

        //Update
        [HttpGet]
        public IActionResult Update(int id)
        {
           ViewBag.Action = "Update";
           ViewBag.Categories = _categories;
           var Product = _LifestyleRepository.GetProductById(id);
           return View("AddUpdate",Product);
        }

        //ManageProduct
        [HttpPost]//Sends data to the server e.g Submitting a form
        public ActionResult ManageProduct(Product product)
        {
            if (ModelState.IsValid) /*validate the data sent to a controller action from a form or other client-side submission*/
            {
                //Adding a new product, it's id is equal to Zero
                if (product.ProductID == 0)
                {
                    _LifestyleRepository.AddProduct(product);
                    //Store temporary lived messages or text
                    TempData["Message"] = $"{product.ProductName}  haves been successfully added.";
                } //Update the product since it has it's own id
                else
                {
                    _LifestyleRepository.UpdateProduct(product);
                    TempData["Message"] = $"{product.ProductName} has been successfully Updated.";
                }
                _LifestyleRepository.saveChanges();
                return RedirectToAction("Product");
            }
            else
            {
                //Ensures the application doesn't break during run-time
                ViewBag.Action = "Save";
                ViewBag.Categories = _categories;
                return View("AddUpdate",product);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = _LifestyleRepository.GetProductById(id);
              
            // return View("Delete",product);-still works but stating the view is not neccessary
            ViewBag.Action = "Delete";
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            //Add hidden properties to the form for every
            ////Use ModelState isValid, to validate if the actual product is passed or not
            //if (ModelState.IsValid)
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Product");
            //}

        _LifestyleRepository.DeleteProduct(product);
         TempData["Message"] = $"{product.ProductName} has been successfully deleted";
         _LifestyleRepository.saveChanges();
         return RedirectToAction("Product");

        }
    }
}

VP_Lifestyle/Controllers/RestoranController.cs
using Microsoft.AspNetCore.Mvc;

namespace VP_Lifestyle.Controllers
{
    public class RestoranController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Service()
        {
            return View();
        }
    }
}

VP_Lifestyle/Views/Shared/_AdminLayout.cshtml
@{
    // Referencing the shared layout
    // Layout = "_Layout";
    string controller =
           ViewContext.RouteData.Values["controller"].ToString().ToLower();
    string action = 
            ViewContext.RouteData.Values["action"].ToString().ToLower();

}


<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>VP_Admin - @ViewBag.Title</title>

    <link href="/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <!-- Custom Style -->
    <link rel="stylesheet" href="/css/style.css" />
</head>
<body>
    <!-- Navbar & Hero Start -->
    <div class="container-fluid position-relative p-0">
        <nav class="navbar navbar-expand-md bg-dark" data-bs-theme="dark">
            <a class="navbar-brand p-0" href="/"> @* returns the client to the home page *@
                <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Restoran</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="bg-primary navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navCollapse">
                <div class="navbar-nav ms-auto py-0 pe-4">
                    <a class="nav-item nav-link 
                       @(controller=="adminhome" && action=="index" ? "active" : "")
                       " asp-controller="AdminHome" asp-action="Index">Admin Home</a>
                    <a class="nav-item nav-link
                        @(controller =="adminproduct" && action=="product" ? "active" : "")"
                       asp-controller="AdminProduct" asp-action="Product">Admin Product</a>
                    <a class="nav-item nav-link
                       @(controller=="admincategory" && action=="category" ? "active " : "")"
                       asp-controller="AdminCategory" asp-action="Category">Admin Category</a>
                </div>
                <a class="btn btn-primary py-2 px-4
                   @(controller =="restoran" && action == "index"? "active" : "")"
                   asp-controller="Restoran" asp-action="Index">Exit Admin</a>
            </div>
        </nav>
    </div>

    <div>
        @RenderBody()
    </div>
    <!--Footer-->
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Reservation</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                    <h5 class="text-light fw-normal">Monday - Saturday</h5>
                    <p>09AM - 09PM</p>
                    <h5 class="text-light fw-normal">Sunday</h5>
                    <p>10AM - 08PM</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; 2024, All Right Reserved.

                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- Bootstrap Bundle with Popper -->
    <script src="/js/bootstrap.bundle.min.js"></script>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>
</html>

VP_Lifestyle/Views/Shared/_Layout.cshtml
@{
    //Used to mark a page active, when it's clicked on.
    string controller =
             ViewContext.RouteData.Values["controller"].ToString();
    string action =
            ViewContext.RouteData.Values["action"].ToString();  
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VP - @ViewBag.Title</title>

   

    <link href="/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <!-- Custom Style -->
    <link rel="stylesheet" href="/css/style.css" />
</head>

<body>
    <!-- Navbar & Hero Start -->
    <div class="container-fluid position-relative p-0">
        <nav class="navbar navbar-expand-md bg-dark" data-bs-theme="dark">
            <a class="navbar-brand p-0" href="/">
                <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Restoran</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="bg-primary navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navCollapse">
                <div class="navbar-nav ms-auto py-0 pe-4">
                    <a class="nav-item nav-link 
                       @(controller=="Restoran" && action=="Index" ? "active" : "")
                       "asp-controller="Restoran" asp-action="Index">Home</a>
                    <a class="nav-item nav-link
                       @(controller=="Restoran" && action=="About" ? "active" : "" )
                        " asp-controller="Restoran" asp-action="About">About</a>
                    <a class="nav-item nav-link
                        @(controller =="Restoran" && action=="Service" ? "active" : "")"
                         asp-controller="Restoran" asp-action="Service">Service</a>
                    <a class="nav-item nav-link
                       @(controller=="Product" && action=="Menu" ? "active" : "")"
                        asp-controller="Product" asp-action="Menu">Menu</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">VP-More</a>
                        <div class="dropdown-menu m-0">
                            <a href="/booking.html" class="dropdown-item">Booking</a>
                            <a href="/team.html" class="dropdown-item">Our Team</a>
                            <a href="/testimonial.html" class="dropdown-item">Testimonial</a>
                        </div>
                    </div>
                    <a href="/contact.html" class="nav-item nav-link">Contact</a>
                </div>
                <a class="btn btn-primary py-2 px-4
                   @(controller.StartsWith("Admin") ?"active":"")"
                    asp-controller="AdminHome" asp-action="Index">Admin</a>
            </div>
        </nav>
    </div>

    <!-- Main Content -->
    <main>
        @RenderBody()
    </main>

    <!--Footer-->
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Reservation</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                    <h5 class="text-light fw-normal">Monday - Saturday</h5>
                    <p>09AM - 09PM</p>
                    <h5 class="text-light fw-normal">Sunday</h5>
                    <p>10AM - 08PM</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; 2024, All Right Reserved.
                       
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    

    <!-- Bootstrap Bundle with Popper -->
    <script src="/js/bootstrap.bundle.min.js"></script>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>
</html>